name: voltagesensing_env_py2
dependencies:
- future=0.14.3=py27_0
- ipython=3.1.0=py27_0
- ipython-notebook=3.1.0=py27_2
- jinja2=2.7.3=py27_2
- jsonschema=2.4.0=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_1
- mistune=0.5.1=py27_1
- numpy=1.9.2=py27_0
- pandas=0.16.1=np19py27_0
- pip=6.1.1=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.10.4=py27_1
- pyreadline=2.0=py27_0
- python=2.7.9=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyzmq=14.6.0=py27_0
- scipy=0.15.1=np19py27_0
- seaborn=0.5.1=np19py27_0
- setuptools=16.0=py27_0
- six=1.9.0=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- tornado=4.1=py27_0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
